### ISSUE TITLE
Isn't this illigal? 

### ISSUE THREAD

**Issue by GabenCrying** [ec-/Quake3e#145]
Arn't I supposed to, like, ya'know, BUY the GAME? WHY ARE YOU DISTRIBUTING A GAME ILLIGALLY YOU F******* MORONS!!!!!!!!!

**Comment by ec-** [comment]
`This repository does not contain any game content so in order to play you must copy the resulting binaries into your existing Quake III Arena installation`

**Comment by The-Gig** [comment]
No, this is not illegal.

While Quake3 assets are still under copyright, its engine and gamelogic source code has been released under GPL license since 2005. This allowed the creation of many id tech 3 forks, such as ioquake3 and Quake3e, which ported the game to more platforms and added new features. But you still need to own the game to get the pk3 (assets) files.

Otherwise, you can download and play OpenArna, which is a standalone game that uses its own free assets instead of the Q3 ones.
