### ISSUE TITLE
Feature Request: ATI TruForm Mode/Tesselation rendering

### ISSUE THREAD

**Issue by Bittermens** [ec-/Quake3e#153]
Something that was rediscovered a while ago at VOGONS forums, Quake 3 Supported ATI TruForm tesselation mode which gave to all of the Q3A models quality on par with late 2000's models

https://imgur.com/a/TcV1qcC

Sadly this is limited only to FTWQW and even there they never finished completely, it would be possible to implement this again as a option using GL and Vulkan? i would love to see something that paul steed fell in love with.

**Comment by ensiform** [comment]
Pretty sure it was available in the original Wolfenstein Enemy: Territory releases, but it was stripped from the GPL release presumably due to licensing issues. FTEQW must have an alternative method for doing it? Seems kinda not great idea to implement since it is only for ATI cards and the extensions are non existent on today's AMD cards plus no nvidia support.

**Comment by Screamerofstars** [comment]
modern GL and vulkan supports tesselation out of box with a few tricks, and there were patches to add it back to other games recently, there is thread at vogons that covers this with more precision.

and those screenshots are running on normal open GL, no need of ATI cards at all.

**Comment by FrankyMc** [comment]
It would be great if we could emulate this on all GPUs

**Comment by ensiform** [comment]
The code for it was never included in the quake3 gpl source release all the years ago though.

**Comment by Screamerofstars** [comment]
it was tested recently at VOGONS forums, it works mostly under FTEQW, but not all models are affected by it, Spike at celephais may know how he had done it.

Also Raven at VOGONS has more info on how to make it work, as he tested on original hardware, and all models works on it, even the likes of Tank Jr under TruForm looks something out of late idtech 3/early idtech4 games, plus GL and vulkan has calls for it since FTE has it.

**Comment by garoto** [comment]
Sharing some forum thread links would be handy...

**Comment by Screamerofstars** [comment]
Original thread with games that supported it under openGL
https://www.vogons.org/viewtopic.php?t=83000

Dgvoodoo2 thread about it, is more related to directx Truform which morrowind and UT used
https://www.vogons.org/viewtopic.php?t=83037

VOGONS wiki about the API
https://www.vogonswiki.com/index.php/TruForm

**Comment by ec-** [comment]
> VOGONS wiki about the API
>https://www.vogonswiki.com/index.php/TruForm

as it says:

> Truform needs to be implemented in the models with flags that identify areas to be tessellated.

so won't be implemented as no such models available in a reasonable quantity
