### ISSUE TITLE
config and server

### ISSUE THREAD

**Issue by gregorypiro** [ec-/Quake3e#184]
Hi. Im running on RHEL 9. Just wondering why some of my zzz files are not loaded. Why i cant change some settings like crosshaircolor i changed to 3 so its yellow but it doesnt change. Why guys? Second thing how do I run the server that i can play locally. Need help with that simple issues as im new linux user. Hope you give me some guidance. Thanks a lot. Greetings.

**Comment by ensiform** [comment]
What mod (fs_game) is loaded? Crosshair coloring probably isn't available in the stock game without fixed shaders.

Check to see your zzz pk3s are listed in the /path command. Check for errors in the console. You have provided so little information that is not really possible to give exact advice to fix

**Comment by gregorypiro** [comment]
The strange thing is that commands cg_croshairsize and cg_drawcroshair work properly. Even more now im thinking what is going on. And the my zzz-file is not loading as well. Will try again chmod 755 for that one. Whats going on?

**Comment by The-Gig** [comment]
I assume you are using your zzz pk3 to play _locally_, right? Because custom pk3s will be ignored when connecting to "pure" external servers.

Also, I'm not familiar with q3plus mod, but in general, if it has got a "crosshair shows health" option and it's enabled, your custom crosshair color will be ignored, as the crosshair will automatically change color (typically from white to yellow to red, I think) when your health will go low...

About running a server, you can either run a "listening server" (the same process running as both client and server) or a dedicated server (a process running server only; you can play as client on the same machine from a different process). Dedicated mode is typically set from OS command line (+set dedicated 1 for LAN play; +set dedicated 2 to broadcast the existence of your server on the master server, but you need to correctly configure port forwarding in your modem/router/firewall to allow incoming traffic).

**Comment by gregorypiro** [comment]
The file zzz i used to play on windows always worked on my favourite server. Just under linux (RHEL 9) have such a problem.

In second case you are right, and helped me a lot. Crosshairhealth indeed was enabled and it really worked.

Third. I think i catch you. However ded 1 or 2 i cant see it on the list. I even +set net_ip and net_port and tried connect through specify and it didnt pass. Just wondering what command put there to be visible. For your knowledge this server must be only for me so easiest way is better.

**Comment by The-Gig** [comment]
About the custom pk3, to work online either the server has sv_pure 0, which is uncommon (that should be used for testing only, as can bring unexpected results), or the server has got the same pk3.

About ginding your server, are you searching for it from another machine in your LAN? From the same machine? _If you are not passing through internet_, an OS firewall issue is more likely than a router issue.

Years ago I wrote what I knew about setting up a game server here: <https://openarena.fandom.com/wiki/Manual/Multiplayer>, <https://openarena.fandom.com/wiki/Manual/Multiplayer/Advanced>. Despite being OpenArena-focused, many things should be also applicable to q3 and its forks.

**Comment by gregorypiro** [comment]
@The-Gig this is most probably sv 0 (but it is also possible that server has same pk3- its not really worth our focus) however im not 100% sure this is not that important. The file quiet the announcer and the other changes the flag nothing dangerous.

Im looking for a server from my computer to only my computer lets say. If you think OS firewall has "bigger priority" thats fine, something to do, to go through.....tonight.

Definitally i will read your articles have some time so it will be a pleasure.
