### ISSUE TITLE
Changing r_gamma has no permanent effect

### ISSUE THREAD

**Issue by shapirus** [ec-/Quake3e#75]
My r_gamma setting is different from the default.

Issue: when Quake3e is started, the screen is initially rendered with the gamma setting that is set in the config file, but then gets reset to the state as if r_gamma were set to 1.

If I change its value in runtime, then, again, the new setting stays (in terms of what I see on the screen) for a second or two and then gets reset back to default, no matter what value is set in the config file.

The renderer is set to "opengl". Vulkan is not available for my system/hardware, apparently. Debian Testing, Radeon HD 7750 with FOSS drivers.

(works fine with ioquake3.)

**Comment by ensiform** [comment]
Are you compiling with dynamic renderer enabled? I think the prebuilt binaries of Q3e does not contain the functionality to switch. It'll be either Vulkan or OpenGL. Keep in mind that you might have tons of extra cvars since you are polluting with ioquake3 configs.

I was under the impression that Vulkan was near universally supported except really old cards under Linux with Mesa on non-dedicated GPUs.

It wouldn't hurt to make sure to use SDL backend for this. As it is recommended for Linux now I believe @ec- can verify. Sounds like a conflict with driver<>X11 gamma ramp. If your driver supports FBO's I would highly recommend using `r_fbo 1` as this will eliminate the usage of driver/platform gamma and use an ARB shader.

**Comment by ec-** [comment]
@shapirus feel free to reopen if this is still an issue
